version: '3'
services:
  kostal:
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  - NB_USER=appuser
      #  - NB_UID=1001
      #  - NB_GID=101
    #image: kostal2mqtt:latest
    #image: wolfi82/kostal2mqtt:latest
    container_name: kostal2mqtt
    restart: unless-stopped
    user: "0"
    volumes:
        - ./:/app/


### config examples for future extensions
  #  volumes:
  #  - ./volumes/influxdb/data:/var/lib/influxdb
  #  - ./backups/influxdb/db:/var/lib/influxdb/backup
  #  networks:
  #  - iotstack_nw


#    command:
#    - '--config.file=/etc/prometheus/config.yml'
#    - '--storage.tsdb.path=/data'


