{
 "title": "Kostal PV Wechselrichter",
 "tags": [
  "Bernza",
  "Python",
  "Kostal PV"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "influxdb", "query": "influxdb" },
   { "name": "PV_database", "query": "influxdb" },
   { "name": "solcast_database", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Status Hausanschluss",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Power_curr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"SML_Total_out\") FROM \"mqtt_consumer\" WHERE (\"topic\" = 'tele/emh_ehz/SENSOR') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "SML_Power_act" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "tele/emh_ehz/SENSOR" }
     ]
    }
   ]
  },
  {
   "title": "WR Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_STATE_flag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "WR DC States",
   "type": "stat",
   "description": "Phasenselektiv",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING1_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING2_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING3_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "Energy actual",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "CPU Busy",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_ENERGY_actual" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "Energy daily",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Energy daily",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_ENERGY_daily" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "Last value",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Energy daily",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_ENERGY_daily" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "kostal2mqtt",
   "type": "stat",
   "description": "python script",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Uptime",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_status",
     "select": [
      [
       { "params": [ "uptime_ns" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "kostal2mqtt" }
     ]
    }
   ]
  },
  {
   "title": "Energy Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Energy total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_ENERGY_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "WR Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_STATE_flag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "Einspeisung WR",
   "type": "stat",
   "description": "Phasenselektiv",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_OUT_PHASE1_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_OUT_PHASE2_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_OUT_PHASE3_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "WR Erzeugung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Energy actual",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"PIKO_ENERGY_actual\") FROM \"mqtt_consumer\" WHERE (\"topic\" = 'KOSTAL') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PIKO_ENERGY_actual" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    { "target": "sun_altitude" },
    {
     "alias": "pv_estimate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solcast",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "pv_estimate" }
     ]
    },
    {
     "alias": "pv_estimate10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solcast",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "pv_estimate10" }
     ]
    },
    {
     "alias": "pv_estimate90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solcast",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "pv_estimate90" }
     ]
    }
   ]
  },
  {
   "title": "Forecast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "solcast_pv_est",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solcast",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "pv_estimate" }
     ]
    },
    {
     "alias": "solcast_pv_est10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solcast",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "pv_estimate10" }
     ]
    },
    {
     "alias": "solcast_pv_est90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solcast",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "pv_estimate90" }
     ]
    },
    {
     "alias": "actual",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_ENERGY_actual" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "Stromzähler total Out last 14d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Total_Out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT difference(last(\"SML_Total_out\")) FROM \"mqtt_consumer\" WHERE (\"topic\" = 'tele/emh_ehz/SENSOR') AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "SML_Total_in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "tele/emh_ehz/SENSOR" }
     ]
    },
    {
     "alias": "Total_Out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "SML_Total_in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "emh_ehz/tele/SENSOR" }
     ]
    }
   ]
  },
  {
   "title": "Stromzähler total Out last 14d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Total_Out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT difference(last(\"SML_Total_out\")) FROM \"mqtt_consumer\" WHERE (\"topic\" = 'tele/emh_ehz/SENSOR') AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "SML_Total_in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "tele/emh_ehz/SENSOR" }
     ]
    },
    {
     "alias": "Total_Out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "SML_Total_in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "emh_ehz/tele/SENSOR" }
     ]
    }
   ]
  },
  {
   "title": "PV generation last 14d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Total_In",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT non_negative_difference(last(\"PIKO_ENERGY_total\")) FROM \"mqtt_consumer\" WHERE (\"topic\" = 'KOSTAL') AND $timeFilter GROUP BY time(1d) fill(null)\n",
     "select": [
      [
       { "params": [ "SML_Total_in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "tele/emh_ehz/SENSOR" }
     ]
    }
   ]
  },
  {
   "title": "PV generation last24hrs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Total_In",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT non_negative_difference(last(\"PIKO_ENERGY_daily\")) FROM \"mqtt_consumer\" WHERE (\"topic\" = 'KOSTAL') AND $timeFilter GROUP BY time(1h) fill(null)\n",
     "select": [
      [
       { "params": [ "SML_Total_in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "tele/emh_ehz/SENSOR" }
     ]
    }
   ]
  },
  {
   "title": "Aktuell",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Solcast API Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "alias": "ctr_est_act_timed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "Counter_API_est_act_timed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "solcast" }
     ]
    },
    {
     "alias": "ctr_forecasts_timed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "Counter_API_forecasts_timed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "solcast" }
     ]
    },
    {
     "alias": "ctr_forecasts_timed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "Counter_reset" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "solcast" }
     ]
    },
    {
     "alias": "ctr_req_total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "Counter_API_req_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "solcast" }
     ]
    },
    {
     "alias": "ctr_req_within_limits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "Counter_API_req_within_limit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "solcast" }
     ]
    },
    {
     "alias": "ctr_retries_total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "Counter_API_retries_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "solcast" }
     ]
    }
   ]
  },
  {
   "title": "Ertrag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Out Leistung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Phase1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_OUT_PHASE1_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "Phase2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_OUT_PHASE2_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "Phase3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_OUT_PHASE3_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "Energy Actual",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_ENERGY_actual" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "Out Spannung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Phase1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_OUT_PHASE1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "Phase2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_OUT_PHASE2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "Phase3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_OUT_PHASE3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "WR Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Phase1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_OUT_PHASE1_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "Phase2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_OUT_PHASE2_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "Phase3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_OUT_PHASE3_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "wr_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_STATE_flag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "WR DC String Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "String1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING1_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "String2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING2_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "String3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING3_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "wr_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_STATE_flag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "Kostal PV Wechselrichter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "String1",
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "CPU Busy",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING1_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "String2",
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "CPU Busy",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING2_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "String3",
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "CPU Busy",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING3_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "Strom",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "String1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING1_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "String2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING2_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "String3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING3_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "Spannung",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "String1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "String2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "String3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "IN Strom",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "String1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING1_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "String3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING3_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "IN Spannung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "String1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    },
    {
     "alias": "String3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "IN Strom delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "String1-String3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"PIKO_IN_STRING1_current\") - mean(\"PIKO_IN_STRING3_current\") FROM \"mqtt_consumer\" WHERE (\"topic\" = 'KOSTAL') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING1_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  },
  {
   "title": "IN Spannung delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "String1-String3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"PIKO_IN_STRING1_voltage\") - mean(\"PIKO_IN_STRING3_voltage\") FROM \"mqtt_consumer\" WHERE (\"topic\" = 'KOSTAL') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PIKO_IN_STRING1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "KOSTAL" }
     ]
    }
   ]
  }
 ]
}